pull_request_rules:
  - name: Auto-approve PRs with auto-ai label
    conditions:
      - label=auto-ai
      - draft=FALSE
    actions:
      review:
        type: APPROVE
        message: |
          ✅ Auto-approved by Mergify (label: auto-ai).

  - name: Auto-merge AI-approved PRs
    conditions:
      - label=auto-ai
      - check-success=build
      - approved-reviews-by>=1
      - draft=FALSE
    actions:
      merge:
        method: squash
