pull_request_rules:
  - name: ✅ Auto-approve and merge any non-draft PR into main if checks pass
    conditions:
      - base=main
      - -draft
      - check-success~=.*
    actions:
      review:
        type: APPROVE
        message: |
          ✅ Auto-approved by Mergify AI (checks passed, base=main)
      merge:
        method: squash