services:
  db:
    image: postgres:17.0
    restart: always
    volumes:
      - '/var/lib/postgresql/data:/var/lib/postgresql/data'
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: java_be_genai_plgrnd
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -D java_be_genai_plgrnd" ]
      interval: 30s
      timeout: 10s
      retries: 5
  backend:
    build: ./
    depends_on:
      - db
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: root
      DB_PASSWORD: root