name: AI Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run AI review
        uses: kriasoft/ai-pr-reviewer@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          model: openrouter/gpt-4
          openai-api-key: ${{ secrets.OPENROUTER_API_KEY }}
          prompt: |
            You are a senior Java engineer.
            Review changes related to controllers, services and test logic.
            Focus on null checks, bad naming and redundancy.
